name: Sonarqube Scanner

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Sonarqube Scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.2.0
        with:
          fetch-depth: 0  
      - uses: sonarsource/sonarqube-scan-action@main
        env:
          SONAR_TOKEN: sqp_d987a78df4fb9afc8215cf205380d358ae280393
          SONAR_HOST_URL: http://localhost:9000
          sonar.projectKey: sonargithub
          sonar.projectName: sonargithub
          
    
